### PR TITLE
Fix replay generation

### LINKED ISSUE #57: Fix replay generation
I spent some time today putting all the pieces in place for replay generation. Everything is there now, but it doesn't work.

### PR DESCRIPTION
**Pull request by tfausak**
This is a work in progress. It aims to fix #57.

### CODE REVIEW

**Comment by tfausak** [comment]
I think the class property map is correct. I still can't round-trip a replay, and I think the problem is compressed words. Usually they have relatively high limits — somewhere between 30 and 1024. Since my class property map only has the properties that are actually used in the replay, the number of properties per class is very low, sometimes as low as 2.

```
Putting property id 0 of 2 for "TAGame.Ball_TA"."TAGame.Ball_TA:GameEvent" = ValueFlaggedInt (FlaggedIntValue {flaggedIntValueFlag = Boolean {booleanUnpack = True}, flaggedIntValueInt = 6})
Putting property id 2 of 2 for "TAGame.Ball_TA"."TAGame.RBActor_TA:ReplicatedRBState" = ValueRigidBodyState (RigidBodyStateValue {rigidBodyStateValueSleeping = Boolean {booleanUnpack = True}, rigidBodyStateValuePosition = Vector {vectorX = 0, vectorY = 0, vectorZ = 93}, rigidBodyStateValueRotation = Vector {vectorX = -1.0000305, vectorY = -1.0000305, vectorZ = -1.0000305}, rigidBodyStateValueLinearVelocity = Nothing, rigidBodyStateValueAngularVelocity = Nothing})

Getting replication for actor 0
Getting existing replication properties for object 0 "Archetypes.Ball.Ball_Default" class 1 "TAGame.Ball_TA"
Getting property 0 of 2 "TAGame.Ball_TA:GameEvent"
Got property ValueFlaggedInt (FlaggedIntValue {flaggedIntValueFlag = Boolean {booleanUnpack = True}, flaggedIntValueInt = 6})
Getting property 0 of 2 "TAGame.Ball_TA:GameEvent" -- WRONG
Got property ValueFlaggedInt (FlaggedIntValue {flaggedIntValueFlag = Boolean {booleanUnpack = True}, flaggedIntValueInt = 16777234})
```

I think compressed words don't work for limits that low. I have something wrong in both my serializer and deserializer.

**Comment by tfausak** [comment]
I figured QuickCheck would have caught this, but it didn't. The `Arbitrary` instance for `CompressedWord` generates a limit between `1` and `maxBound`. Since the limit is a `Word`, the `maxBound` is `18446744073709551615` (on my machine). And since QuickCheck uses a normal distribution, the odds of getting a limit of (say) 2 are very low. 

Changing the limit to `10` immediately found a problem.

```
      can round trip CompressedWord:   FAIL
        Falsifiable (after 2 tests): 
        Expected:  CompressedWord
          { compressedWordLimit = 8 , compressedWordValue = 8 }
        Actual: CompressedWord
          { compressedWordLimit = 8 , compressedWordValue = 0 }
        CompressedWord {compressedWordLimit = 8, compressedWordValue = 8}
```

**Comment by tfausak** [comment]
Yup. With a limit of `2`, my code only thinks to read or write a single bit.

```
putting compressed word: limit = 2; maxBits = 1; value = 2
getting compressed word: limit = 2; maxBits = 1
```

File: library/Octane/Type/CompressedWord.hs [hunk 1]
```diff
@@ -43,7 +43,8 @@ $(OverloadedRecords.overloadedRecord Default.def ''CompressedWord)
 instance BinaryBit.BinaryBit CompressedWord where
   getBits n = do
     let limit = fromIntegral n
-    value <- getStep limit (bitSize limit) 0 0
+    let maxBits = bitSize limit
+    value <- getStep limit maxBits 0 0
```
Comment (tfausak) [inline library/Octane/Type/CompressedWord.hs]: This is unnecessary. I bound it to a local value so I could print it out, but that's not necessary anymore.

File: library/Octane/Type/CompressedWord.hs [hunk 2]
```diff
@@ -89,7 +90,18 @@ fromCompressedWord compressedWord = compressedWord & #value & fromIntegral
...
+  case x of
+    2 -> 2
+    4 -> 3
+    8 -> 4
+    16 -> 5
+    32 -> 6
+    64 -> 7
+    128 -> 8
+    256 -> 9
+    512 -> 10
```
Comment (tfausak) [inline library/Octane/Type/CompressedWord.hs]: Obviously powers of 2 are special. If `x = 2 ^ n`, then `bitSize x = n + 1`.

File: library/Octane/Type/Replay.hs [hunk 3]
```diff
@@ -158,72 +160,72 @@ fromOptimizedReplay optimizedReplay = do
...
   :: (Monad m)
   => Replay -> m OptimizedReplay.OptimizedReplay
-toOptimizedReplay replay = do
-  let [version1, version2] =
-        replay & #version & Version.versionBranch & map Word32.toWord32
-  -- Key frames aren't important for replays. Mark the first frame as a key
-  -- frame and the rest as regular frames.
+toOptimizedReplay replay
+                  -- Key frames aren't important for replays. Mark the first frame as a key
+                  -- frame and the rest as regular frames.
```
Comment (tfausak) [inline library/Octane/Type/Replay.hs:166]: hindent does not like comments like this.

File: library/Octane/Type/Replay.hs [hunk 4]
```diff
@@ -158,72 +160,72 @@ fromOptimizedReplay optimizedReplay = do
...
+                   propertiesByClass & Map.findWithDefault [] className &
                    List.List
              CacheItem.CacheItem classId parentCacheId cacheId properties) &
         List.List
   pure
     OptimizedReplay.OptimizedReplay
-    { OptimizedReplay.optimizedReplayVersion1 = version1
-    , OptimizedReplay.optimizedReplayVersion2 = version2
+    { OptimizedReplay.optimizedReplayVersion1 = 868
+    , OptimizedReplay.optimizedReplayVersion2 = 12
```
Comment (tfausak) [inline library/Octane/Type/Replay.hs]: Hard coding these values is unfortunate. I probably need a `latestVersion` constant to use instead. But they have to be constants — I don't want to support writing arbitrary replay versions. Then I'd have to do things like make sure the property even existed in that version. Not worth it.

File: library/Octane/Utility/ClassPropertyMap.hs [hunk 5]
```diff
@@ -61,13 +61,19 @@ getClassCache :: Replay.ReplayWithoutFrames
...
+    map
       (\cacheItem -> do
          let classId = cacheItem & #classId & Word32.fromWord32
-         className <- Map.lookup classId classNames
+         let className =
+               case Map.lookup classId classNames of
+                 Nothing ->
+                   error
+                     ("could not find class name for id " ++
+                      show classId ++ " in " ++ show classNames)
```
Comment (tfausak) [inline library/Octane/Utility/ClassPropertyMap.hs:72]: This blows up instead of silently ignoring failures now.

File: library/Octane/Utility/ClassPropertyMap.hs [hunk 6]
```diff
@@ -86,7 +92,8 @@ getParentClassId className parentCacheId xs =
       xs & filter (\(_, name, _, _) -> name == parentClassName) &
       filter (\(_, _, cacheId, _) -> cacheId == parentCacheId) &
       map (\(classId, _, _, _) -> classId) &
-      Maybe.listToMaybe
+      Maybe.listToMaybe &
+      Maybe.maybe (getParentClassId StrictText.empty parentCacheId xs) Just
```
Comment (tfausak) [inline library/Octane/Utility/ClassPropertyMap.hs]: I should probably make `className` a `Maybe` and pass `Nothing` instead of using `empty` as a sentinel value.

File: library/Octane/Utility/Generator.hs [hunk 7]
```diff
@@ -57,28 +57,32 @@ generateStream
   -> List.List ClassItem.ClassItem
   -> List.List CacheItem.CacheItem
   -> Stream.Stream
-generateStream frames objects _names _classes cache = do
-  let context = makeContext objects cache
+generateStream frames objects _names classes cache = do
+  let context = makeContext objects classes cache
```
Comment (tfausak) [inline library/Octane/Utility/Generator.hs:61]: Obviously you need the classes to generate the stream.

File: library/Octane/Utility/Parser.hs [hunk 8]
```diff
@@ -132,7 +132,25 @@ getStream replay = do
...
+    map
+      (\(k1, v1) ->
+         show k1 ++
+         "\n" ++
+         (v1 & IntMap.toAscList &
+          map (\(k2, v2) -> "\t" ++ show k2 ++ "\t" ++ show v2) &
+          unlines)) &
+    ("CLASS PROPERTY MAP" :) &
+    unlines &
+    trace
```
Comment (tfausak) [inline library/Octane/Utility/Parser.hs:151]: It may not be necessary to print these out. On the other hand, it would be useful to debug problems like #37. I guess I might as well leave it in.

**Comment by tfausak** [comment]
Bad news:
1. The tests are broken.
2. The generated replay crashes Rocket League. 

😢
